export const FIND_ALL_FLIGHTS = 'FIND_ALL_FLIGHTS';
export const SET_ALL_FLIGHTS = 'SET_ALL_FLIGHTS';

export const DEPARTURE = 'DEPARTURE';
export const ARRIVAL = 'ARRIVAL';

export const FIND_AVAILABLE_FLIGHTS = 'FIND_AVAILABLE_FLIGHTS';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
